### ISSUE TITLE
is this project still under maintain ?

### ISSUE THREAD

**Issue by mrtuvn** [magento/baler#74]
I see this reference still mention in magento clould or devdocs but it's not recommended in production. Just wonder adobe/owner/stakeholders still keep funding this or let this die in peace
"Because Baler is currently in alpha release, we do not recommend using it in Production environments."
https://devdocs.magento.com/cloud/env/variables-build.html#scd_use_baler
Seem related with https://github.com/magento/baler/issues/70

**Comment by Leland** [comment]
https://github.com/magento/devdocs/pull/7876. 

From what I understand, it's been completely abandoned internally for well over a year. Not only is it "not recommended in production," it flat out does not work anymore on v2.4 without manual customizations.

Anyway, I stripped its recommendation from the Devdocs JS pages, and it has since been removed from Lighthouse recommendations. I'd recommend you open a PR out to the devdocs repo adjusting that notice to something more along the lines of a deprecation alert.

**Comment by alexvais** [comment]
@Leland i think thi was not deleted from lighthouse recomendation. 

![Selection_393](https://user-images.githubusercontent.com/6999914/132773153-35f890b4-92f6-4605-9041-6c7430130081.png)

Do you know some other tool to Avoid chaining critical requests ?

**Comment by mrtuvn** [comment]
Reduce amounts of number js load as much as possible. Baler current owner not support i think you have clone this and custom your own way branch. Magepack is also good. But require some commit/patch update. At this point magepack seem more active than baler in my opinion. 2.7.2 just released. 
https://github.com/magesuite/magepack/tree/2.7.2
